// SPDX-FileCopyrightText: 2024 Deutsche Telekom AG, LlamaIndex, Vercel, Inc.
//
// SPDX-License-Identifier: MIT

import type { Metadata } from "next";
import "./style/fonts/index.css";
import "./style/globals.css";
import "./style/telekom.css";

export const metadata: Metadata = {
  title: "Create TSI App",
  description: "Generated by create-tsi",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
